services:
    _defaults:
        autowire: true
        autoconfigure: true
    Flavacaster\SymfonyHttpBundle\:
        resource: '../../src/'
    Flavacaster\SymfonyHttpBundle\ArgumentResolver\RequestPayloadValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
